# Generated by Django 3.2.12 on 2022-03-21 17:19

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(default=None, max_length=11, unique=True, validators=[core.utils.validate_contact_number]),
        ),
    ]
