# Generated by Django 3.2.12 on 2022-03-21 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255)),
                ('destination_iata', models.CharField(max_length=50)),
                ('origin', models.CharField(max_length=255)),
                ('origin_iata', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=255)),
                ('departure', models.DateTimeField()),
                ('arrival', models.DateTimeField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_lines', to='migration_test.order')),
            ],
        ),
    ]
